
services:
    database:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: moneymachine
            MYSQL_DATABASE: moneymachine
        volumes:
            - ./backupDB:/docker-entrypoint-initdb.d
            - db-volume:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 5s
            retries: 1
        ports:
            - '3306:3306'
        container_name: database

    bottrade:
        build:
            context: ./botTrade
            dockerfile: Dockerfile.dev
        depends_on:
            database:
                condition: service_healthy
        ports:
            - '9999:9999'
        env_file: ./botTrade/.env
        volumes:
            - ./botTrade:/app            # Mount local source for hot-reload
            - /app/node_modules          # Prevent overwriting node_modules
        container_name: bottrade

    backend:
        build:
            context: ./webServer
            dockerfile: Dockerfile.dev
        depends_on:
            database:
                condition: service_healthy
        ports:
            - '1234:1234'
            - '7777:7777'
        env_file: ./webServer/.env
        volumes:
            - ./webServer:/app
            - /app/node_modules          
            # - ./certbot/conf:/etc/letsencrypt #Mount for SSL certs

        command: > # đảm bảo prisma client đồng bộ với DB
            sh -c "
            until nc -z database 3306; do sleep 1; done &&
            npx prisma db push &&
            npm start
            "
        container_name: backend

    frontend-user:
        build:
            context: ./frontendUser
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./frontendUser:/app
            - /app/node_modules # avoid overwriting node_modules
    frontend-admin:
        build:
            context: ./frontendAdmin
            dockerfile: Dockerfile.dev
        ports:
            - '3001:3001'
        volumes:
            - ./frontendAdmin:/app
            - /app/node_modules # avoid overwriting node_modules
volumes:
    db-volume:
    log-volume:
